// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nircetjgvswiywpxsbwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pcmNldGpndnN3aXl3cHhzYndqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTcwMTksImV4cCI6MjA2NDI3MzAxOX0.UjZbt1fdTM9rBJY76Cvr-EHeeZn47rKWxNgv1EXCERI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);